name: "emsdk"
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pyodide-build flet
      - uses: mymindstorm/setup-emsdk@v13
        with:
          no-install: true
      - name: Install emsdk
        run: |
          emsdk install $(pyodide config get emscripten_version)
          emsdk activate $(pyodide config get emscripten_version)

      - name: Verify
        run: emcc -v
