name: "emsdk"
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pyodide-build flet
      - uses: mymindstorm/setup-emsdk@v13
        with:
          version: "3.1.45"
          actions-cache-folder: "emsdk-cache"
      - name: Build 
        run: |
          bash build_flet.sh
          cd examples/dist
          mkdir examples
          shopt -s extglob
          mv !(examples) examples
      - name: Upload Site Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages-build
          path: examples/dist
      - name: Deploy Github Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./examples/dist/
